# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: font-linux
description: > # this means to ignore newlines until "baseurl:"
  An icon font containing logos of popular linux distributions for inclusion in websites.
baseurl: "/font-linux" # the subpath of your site, e.g. /blog
url: "https://lukas-w.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
